controller_manager_ns: pr2_controller_manager
controller_list:
  - name: "katana_arm_controller"
    ns: follow_joint_trajectory
    default: true
    joints:
       - katana_motor1_pan_joint
       - katana_motor2_lift_joint
       - katana_motor3_lift_joint
       - katana_motor4_lift_joint
       - katana_motor5_wrist_roll_joint

