controller_manager_ns: moveit_simple_controller_manager
controller_list:
  - name: "jaco_arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
        - jaco_joint_1
        - jaco_joint_2
        - jaco_joint_3
        - jaco_joint_4
        - jaco_joint_5
        - jaco_joint_6


        #- jaco_finger_1_joint
        #- jaco_finger_2_joint
        #- jaco_finger_3_joint
