## from version 0.02.4 on, trajectory_filters takes joint limits from the URDF
## but will override them with values from the yaml configuration file if they
## exist, acceleration parameters however must still be specified in yaml since
## they are not usually found in the urdf
#2.5
#1.3
#1.3
#2.5
#2.5
## the acceleration limits have been calculated using acc_enc2rad(2). The
## acceleration can be either 1 or 2 [encoders / (10 ms)^2]
joint_limits:
  katana_motor1_pan_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.1
    has_acceleration_limits: true
    max_acceleration: 0.4
    angle_wraparound: false
  katana_motor2_lift_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.6
    has_acceleration_limits: true
    max_acceleration: 0.06
    angle_wraparound: false
  katana_motor3_lift_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.6
    has_acceleration_limits: true
    ## unexplicably, the acceleration limits seem to be exactly half of what acc_enc2rad(2) says
    max_acceleration: 0.03
    angle_wraparound: false
  katana_motor4_lift_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.1
    has_acceleration_limits: true
    max_acceleration: 0.07
    angle_wraparound: false
  katana_motor5_wrist_roll_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.1
    has_acceleration_limits: true
    max_acceleration: 0.10
    angle_wraparound: false

  # The finger joints are not needed by the trajectory filters, since
  # the arm trajectory does not involve them. The limits are still listed
  # here for completenesses sake.
  katana_r_finger_joint:
    has_acceleration_limits: true
    max_acceleration: 0.8
    angle_wraparound: false
  katana_l_finger_joint:
    has_acceleration_limits: true
    max_acceleration: 0.8
    angle_wraparound: false
