sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /kinect/depth_registered/points
    max_range: 4.0
    frame_subsample: 1
    point_subsample: 6
    shape_padding: 0
    shape_scale: 1
    filtered_cloud_topic: filtered_cloud

